# Install mysql in insecure mode (meaning you don't have to supply a password randomly generated by mysqld to start the server)
if ! mysql -u root -e 'show databases;' | grep mysql > /dev/null; then
  announce "Initializing mysql"
  # Cannot initialize mysql if the `datadir` has files in it already (could happen from a previous intallation attempt)
  rm -rf /usr/local/var/mysql
  mysqld --initialize-insecure --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql
fi

if ! launchctl list | grep homebrew.mxcl.mysql > /dev/null; then
  announce "Setting mysql as launch item"
  mkdir -p ~/Library/LaunchAgents
  ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
  launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
fi

brew install mysql 
